language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '10'
env:
  matrix:
    - PACKAGE=cherow
      #- PACKAGE=cherow-ts

script: >
  if [ "$TEST_SUITE" != "cherow" ]; then
    # set -e
    lerna run test --scope $PACKAGE
    # set +e
    # lerna run post_coverage --scope $PACKAGE
  else
    lerna run test --scope $PACKAGE
  fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
