language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
env:
  matrix:
    - PACKAGE=cherow
      #- PACKAGE=bar
      #- PACKAGE=baz

script: lerna run test --scope $PACKAGE

branches:
  only:
  - master
