language: node_js
sudo: false
matrix:
  include:
  - node_js: '8'
  - node_js: '10'
  - node_js: 'node'
  - node_js: 'node'
    env: TEST_SUITE=cherow
script: >
  if [ "$TEST_SUITE" != "cherow" ]; then
    set -e
#    npm run coverage
    npm run test
    set +e
    npm run post_coverage
  else
    npm test
  fi
