language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
env:
  matrix:
    - PACKAGE=foo
      #- PACKAGE=cherow
      #- PACKAGE=cherow-ts

script: lerna run test --scope $PACKAGE

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
