language: node_js
sudo: false
matrix:
  include:
  - node_js: '0.12'
  - node_js: '4'
  - node_js: '5'
  - node_js: '6'
  - node_js: '7'
  - node_js: '8'
  - node_js: 'node'
  - node_js: 'node'
    env: TEST_SUITE=cherow
script: >
  if [ "$TEST_SUITE" != "cherow" ]; then
    set -e
    npm run coverage
    set +e
    npm run post_coverage
  else
    npm test
  fi
