version: "{build}"

environment:
  nodejs_version: "8"
  matrix:
    - PACKAGE: "cherow"
    - PACKAGE: "cherow-ts"

branches:
  only:
    - master

matrix:
  fast_finish: true

cache:
  - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - .\node_modules\.bin\lerna bootstrap

before_test:
  - node --version
  - npm --version
  - yarn --version

test_script:
  - .\node_modules\.bin\lerna run test --scope %PACKAGE%

build: off
deploy: off
