version: 2.1

executors:

  docker-circleci:
    parameters:
      node:
        type: string
        default: "10.12"
    working_directory: ~/repo
    docker:
      - image: "circleci/node:<< parameters.node >>-stretch-browsers"

jobs:

  build:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

  lint:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  bundle:
    executor: docker-circleci
    steps:
      - checkout
      - run: npm ci
      - run: npm run bundle

  test:
    executor: docker-circleci
    parameters:
      coverage:
        type: boolean
        default: true
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

workflows:
  build_test:
    jobs:
      - build
      - lint
      - bundle
      - test
